# Generated by Django 4.2.6 on 2023-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('seal', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
