# Generated by Django 4.2.6 on 2023-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='disk',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
