# Generated by Django 4.2.6 on 2023-10-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sebo', '0002_alter_disk_quantity_alter_disk_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disks', models.ManyToManyField(to='sebo.disk')),
            ],
        ),
        migrations.AddField(
            model_name='disk',
            name='artists',
            field=models.ManyToManyField(to='sebo.artist'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='seal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sebo.seal'),
        ),
    ]
