# Generated by Django 4.2.6 on 2023-10-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sebo', '0003_seal_artist_disk_artists_alter_disk_seal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='artists',
        ),
    ]
