# Generated by Django 4.2.6 on 2023-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sebo', '0004_remove_disk_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='disks',
        ),
        migrations.AddField(
            model_name='disk',
            name='artists',
            field=models.ManyToManyField(to='sebo.artist'),
        ),
    ]
